=== WildGenie/nuve/Nuve/Resources/orthography.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT orthography (alphabet, rules)>
<!ATTLIST orthography lang (Tr-TR | Tk-TK | Az-AZ) #REQUIRED>

<!ELEMENT alphabet (consonants, vowels)>

<!ELEMENT consonants (#PCDATA)>

<!ELEMENT vowels (#PCDATA)>

<!ELEMENT rules (rule)+>

<!ELEMENT rule (description, transformation*)>
<!ATTLIST rule
    id CDATA #REQUIRED
    type (First | Next | Previous | Self | Default | None) #REQUIRED>
<!ELEMENT description (#PCDATA)>

<!ELEMENT transformation (conditions?)>
<!ATTLIST transformation 
  action (
              Append |
              AppendTamlamaSuffix |
              DeleteFirstLetter |
              DeleteFirstVowel | 
              DeleteLastLetter | 
              DeleteLastLetterOfNeighbour |
              DeleteLastVowel |
              DoubleLastLetter |
              Replace |
              ReplaceNeighbour |
              LexicalToSurface 
  ) #REQUIRED
  position (Current | Next | Previous) #IMPLIED
  operandOne CDATA #IMPLIED
  operandTwo CDATA #IMPLIED
  flag CDATA #IMPLIED>

<!ELEMENT conditions (condition+)>
<!ATTLIST conditions
  flag ( And | Or ) #REQUIRED>

<!ELEMENT condition EMPTY>
<!ATTLIST condition 
   morpheme (  Previous |
              Next |
              Current
  ) #IMPLIED
  operator (
                EndsWithConsonant |
                EndsWithVowel |
                FirstLetterEquals |
                LastLetterEquals |
                LastVowelEquals |
                MorphemeEquals |
                MorphemeNotEquals |
                HasFlags |
                HasNotFlags |
                PenultVowelEquals |
                StartsWithConsonant |
                StartsWithVowel 
  ) #REQUIRED
  operand CDATA #IMPLIED>

=== WildGenie/nuve/lang/tr/orthography.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE orthography SYSTEM "orthography.dtd">

<orthography lang="Tr-TR">

  <alphabet>
    <consonants>bcçdfgğhjklmnprsştvyýzDCSKYÇP</consonants>
    <vowels>áaâeéıîioóöúûuüUAI</vowels>
  </alphabet>


  <!-- operandOne ve operandTwo string tipinde -->

  <rules>

    <rule id="L_DUSME_UNLU" type="Previous">
      <description>Önce gelen ek ünlü ile bitiyorsa bu ekin başındaki ünlüyü düşür</description>
      <transformation action="DeleteFirstLetter">
        <conditions flag="Or">
          <condition operator="EndsWithVowel" />
        </conditions>
      </transformation>
    </rule>

    <rule id="L_DUSME_UNSUZ" type="Previous">
      <description>Önceki ek ünsüz ile bitiyorsa bu ekin başındaki ünsüzü (kaynaştırma) düşür</description>
      <transformation action="DeleteFirstLetter">
        <conditions flag="Or">
          <condition operator="EndsWithConsonant" />
        </conditions>
      </transformation>
    </rule>

    <rule id="L_DONUSUM_D" type="Previous">
      <description>Önceki ek sert sessiz ile bitirosa D => t değilse D => d</description>
      <transformation action="Replace" operandOne="D" operandTwo="t" flag="all">
        <conditions flag="Or">
          <condition operator="LastLetterEquals" operand="pçtkşsfh" />
        </conditions>
      </transformation>
      <transformation action="Replace" operandOne="D" operandTwo="d" flag="all" />
    </rule>

    <rule id="L_DONUSUM_C" type="Previous">
      <description>Önceki ek sert sessiz ile bitirosa D => t değilse D => d</description>
      <transformation action="Replace" operandOne="C" operandTwo="ç" flag="all">
        <conditions flag="Or">
          <condition operator="LastLetterEquals" operand="pçtkşsfh" />
        </conditions>
      </transformation>
      <transformation action="Replace" operandOne="C" operandTwo="c" flag="all" />
    </rule>

    <rule id="L_DONUSUM_A" type="Previous">
      <description>Önceki ekin son sesli harfi kalın ise A => a değilse A => e </description>
      <transformation action="Replace" operandOne="A" operandTwo="a" flag="all">
        <conditions flag="Or">
          <condition operator="LastVowelEquals" operand="aıouâû" />
        </conditions>
      </transformation>
      <transformation action="Replace" operandOne="A" operandTwo="e" flag="all" />
    </rule>

    <rule id="L_DONUSUM_I" type="Previous">
      <description>Önceki ekin son sesli harfi kalın ise I => ı değilse I => i </description>
      <transformation action="Replace" operandOne="I" operandTwo="ı" flag="all">
        <conditions flag="Or">
          <condition operator="LastVowelEquals" operand="aıouâû" />
        </conditions>
      </transformation>
      <transformation action="Replace" operandOne="I" operandTwo="i" flag="all" />
    </rule>

    <rule id="L_DONUSUM_U" type="Previous">
      <description>Önceki ekin son sesli harfine göre  U => ı, i, u veya ü olur </description>
      <transformation action="Replace" operandOne="U" operandTwo="ı" flag="all">
        <conditions flag="Or">
          <condition operator="LastVowelEquals" operand="aıâ" />
        </conditions>
      </transformation>
      <transformation action="Replace" operandOne="U" operandTwo="i" flag="all">
        <conditions flag="Or">
          <condition operator="LastVowelEquals" operand="eiéáî" />
        </conditions>
      </transformation>
      <transformation action="Replace" operandOne="U" operandTwo="u" flag="all">
        <conditions flag="Or">
          <condition operator="LastVowelEquals" operand="ouû" />
        </conditions>
      </transformation>
      <transformation action="Replace" operandOne="U" operandTwo="ü" flag="all" />
    </rule>

    <rule id="R_YUMUSAMA_pb" type="Next">
      <description>	Sonraki ek ünlü ile başlıyorsa sondaki p => b'ye yumuşar </description>
      <transformation action="Replace" operandOne="p" operandTwo="b" flag="last">
        <conditions flag="Or">
          <condition operator="StartsWithVowel" />
        </conditions>
      </transformation>
    </rule>

    <rule id="R_YUMUSAMA_çc" type="Next">
      <description> Sonraki ek ünlü ile başlıyorsa sondaki ç => c'ye yumuşar </description>
      <transformation action="Replace" operandOne="ç" operandTwo="c" flag="last">
        <conditions flag="Or">
          <condition operator="StartsWithVowel" />
        </conditions>
      </transformation>
    </rule>

    <rule id="R_YUMUSAMA_td" type="Next">
      <description>	Sonraki ek ünlü ile başlıyorsa sondaki t => d'ye yumuşar 	</description>
      <transformation action="Replace" operandOne="t" operandTwo="d" flag="last">
        <conditions flag="Or">
          <condition operator="StartsWithVowel" />
        </conditions>
      </transformation>
    </rule>

    <rule id="R_YUMUSAMA_kğ" type="Next">
      <description>	Sonraki ek ünlü ile başlıyorsa sondaki k => ğ'ye yumuşar 	</description>
      <transformation action="Replace" operandOne="k" operandTwo="ğ" flag="last">
        <conditions flag="Or">
          <condition operator="StartsWithVowel" />
        </conditions>
      </transformation>
    </rule>

    <rule id="R_YUMUSAMA_kg" type="Next">
      <description> Sonraki ek ünlü ile başlıyorsa sondaki k => g'ye yumuşar. çelenk => çelengi </description>
      <transformation action="Replace" operandOne="k" operandTwo="g" flag="last">
        <conditions flag="Or">
          <condition operator="StartsWithVowel" />
        </conditions>
      </transformation>
    </rule>

    <rule id="R_YUMUSAMA_gğ" type="Next">
      <description>	Sonraki ek ünlü ile başlıyorsa sondaki g => ğ'ye yumuşar. psikolog =› psikoloğa	</description>
      <transformation action="Replace" operandOne="g" operandTwo="ğ" flag="last">
        <conditions flag="Or">
          <condition operator="StartsWithVowel" />
        </conditions>
      </transformation>
    </rule>

    <rule id="R_DUSME_SON_UNLU" type="Next">
      <description>
        Gelen ek ünlü ile başlıyorsa son sesli harf düşer.
        ağız =› ağz-a, burun =› burn-um, zehir =› zehr-e
        Ancak ben ağızım ve biz ağızız şeklinde 1. tekil ve çoğul şahıs ekleri geldiğinde bu düşme olmaz.
      </description>
      <transformation action="DeleteLastVowel">
        <conditions flag="And">
          <condition operator="StartsWithVowel" />
          <condition operator="MorphemeNotEquals" operand="EKFIIL_SAHIS_BEN_(y)Um" />
          <condition operator="MorphemeNotEquals" operand="EKFIIL_SAHIS_BIZ_(y)Uz" />
        </conditions>
      </transformation>
    </rule>

    <rule id="R_DUSME_SON_UNLU_EDILGEN" type="Next">
      <description>
        Edilgen eki geldiğinde son ünlünün düşmesi kuralı
        kavur => kavrul
        doğur => doğrul
      </description>
      <transformation action="DeleteLastVowel">
        <conditions flag="Or">
          <condition operator="MorphemeEquals" operand="FY_EDILGEN_Ul_(U)n" />
        </conditions>
      </transformation>
    </rule>

    <rule id="R_CIFTLESME_SON_UNSUZ" type="Next">
      <description>
        hat›hatt-ı, ret›redd-i , serhat›serhadd-i
      </description>
      <transformation action="DoubleLastLetter">
        <conditions flag="Or">
          <condition operator="StartsWithVowel" />
        </conditions>
      </transformation>
    </rule>

    <rule id="F_OZEL_su" type="First">
      <description>
        Gelen ek sesli ile başlıyorsa veya IC_SAHIPLIK_O_(s)U, IC_HAL_ILGI_(n)Un eklerinden biri ise
        sona y karakteri ekle
      </description>
      <transformation action="Append" operandOne="y">
        <conditions flag="Or">
          <condition operator="StartsWithVowel" />
          <condition operator="MorphemeEquals" operand="IC_SAHIPLIK_O_(s)U" />
          <condition operator="MorphemeEquals" operand="IC_HAL_ILGI_(n)Un" />
        </conditions>
      </transformation>
    </rule>

    <rule id="F_OZEL_N" type="First">
      <description>
        Bazı ek ve kelimelerden sonra araya n sesinin girmesi. kapısıya => kapısına
        kendice => kendince
      </description>
      <transformation action="Append" operandOne="n">
        <conditions flag="Or">
          <condition operator="MorphemeEquals" operand="IC_HAL_YONELME_(y)A" />
          <condition operator="MorphemeEquals" operand="IC_HAL_BULUNMA_DA" />
          <condition operator="MorphemeEquals" operand="IC_HAL_AYRILMA_DAn" />
          <condition operator="MorphemeEquals" operand="IC_HAL_BELIRTME_(y)U" />
          <condition operator="MorphemeEquals" operand="IY_ZARF_CA" />
        </conditions>
      </transformation>
    </rule>

    <rule id="F_OZEL_o" type="First">
      <description> o, bu, şu kökleri bazı ekler için araya n sesi alırlar </description>
      <transformation action="Append" operandOne="n">
        <conditions flag="Or">
          <condition operator="MorphemeEquals" operand="ZAMIR_COGUL_lAr" />
          <condition operator="MorphemeEquals" operand="IC_HAL_YONELME_(y)A" />
          <condition operator="MorphemeEquals" operand="IC_HAL_BULUNMA_DA" />
          <condition operator="MorphemeEquals" operand="IC_HAL_AYRILMA_DAn" />
          <condition operator="MorphemeEquals" operand="IC_HAL_BELIRTME_(y)U" />
          <condition operator="MorphemeEquals" operand="IY_SIFAT_sUz" />
          <condition operator="MorphemeEquals" operand="IY_SIFAT_lU" />
          <condition operator="MorphemeEquals" operand="IY_ISIM_lUK" />
          <condition operator="MorphemeEquals" operand="IY_ISIM_cAğIz" />
          <condition operator="MorphemeEquals" operand="IY_ZARF_CA" />
        </conditions>
      </transformation>
    </rule>

    <rule id="F_OZEL_bana" type="First">
      <description>
        Gelen ek yönelme hal eki ise e => a olur.
        ben => bana, sen => sana
      </description>
      <transformation action="Replace" operandOne="e" operandTwo="a" flag="first">
        <conditions flag="Or">
